### ISSUE TITLE
⚙️ for-all-boosters: rework create_branch and delete_branch commands to use specified branch names

### ISSUE THREAD

**Issue by metacosm** [snowdrop/booster-common#15]
… instead of having to provide one as subcommand argument.

**Comment by metacosm** [comment]
Since #14 makes it possible to pass branch names to operate on as arguments,  these should be used for the `create_branch` and `delete_branch` subcommands.

**Comment by metacosm** [comment]
@geoand can you review, please?

**Comment by geoand** [comment]
@metacosm I added a few comments :)

**Comment by metacosm** [comment]
@geoand please feel free to merge if/when you think all your concerns are properly addressed, btw!

**Comment by geoand** [comment]
I think they have been properly addressed :). But there seems to be a confilict
