### ISSUE TITLE
⚡️for-all-boosters: When releasing a new version, validate that the versions of the booster and the parent match

### ISSUE THREAD

**Issue by geoand** [snowdrop/booster-common#49]
We want to avoid releasing boosters that have miss-matching versions.
An example could be that the pom uses a parent at `1.5.10-x` and the booster itself is at `1.5.12-y` (obviously mixing `1.5.10` and `1.5.12` is undesirable)

**Comment by metacosm** [comment]
Not only this, but the latest version of the parent should also be used, usually… so release should fail and log if the booster doesn't use the latest parent version.

**Comment by geoand** [comment]
Good point!
