### ISSUE TITLE
🐛for-all-boosters: weird behavior with `-p` option

### ISSUE THREAD

**Issue by metacosm** [snowdrop/booster-common#74]
Running `for-all-boosters.sh -pn catalog` results in weird behavior:
```
> spring-boot-cache-booster
	Setting up locally
	redhat: Resetting to remote upstream state
HEAD is now at 60d7193 [booster-release] Update project version to 1.5.13-2-redhat-SNAPSHOT
	master: Executing 'catalog'
	master: Done

	redhat: Executing 'catalog'
	redhat: Done
```

**Comment by geoand** [comment]
What would the correct output be?

**Comment by geoand** [comment]
The catalog seems to generated correctly.
Am I missing something here?

**Comment by metacosm** [comment]
The correct output should be that one branch is processed after the other and operations are performed on both branches. The same behavior is observed with any command. I haven't checked what's going on but the output is at least confusing and maybe indicative of an improper behavior.

**Comment by geoand** [comment]
I need to take another look at it, but I don't think there is a problem
based on how I have used it so far (although I can't be certain until I
examine your example in detail)

**Comment by geoand** [comment]
I can confirm that there is no problem with how the command is operating, but I think that I understand the source of the confusion.

In the output above we:

`redhat: Resetting to remote upstream state`

before anything else. What is confusing is the branch name. That is coming from the fact that on the file system the `redhat` branch is the one that is currently checked out.
To confuse matters even more the message:
`HEAD is now at 60d7193 [booster-release] Update project version to 1.5.13-2-redhat-SNAPSHOT` does not help at all and should probably be removed altogether.

I will create a PR addressing these issues.
