### ISSUE TITLE
⚡️for-all-boosters: add ability to set the runtime version used in OpenShift templates

### ISSUE THREAD

**Issue by metacosm** [snowdrop/booster-common#86]
This should be a separate function since we might want to do it outside of a given release as well.

**Comment by geoand** [comment]
Are we going to be requiring the version as an argument? Will there be a default value?

**Comment by metacosm** [comment]
The idea is to replace the default value that is set in the templates. So yes, this will require passing the value as an argument.

**Comment by geoand** [comment]
Understood, thanks!
