### ISSUE TITLE
⚡️ for-all-boosters: merge run_tests script and add more realistic integration testing

### ISSUE THREAD

**Issue by metacosm** [snowdrop/booster-common#9]
- Assume minishift is available and running but tests should be isolated in specific namespaces

**Comment by geoand** [comment]
We can definitely set this up on our internal infrastructure.
Can you provide a little more info on what you intend to see here?

**Comment by metacosm** [comment]
@geoand true, but the idea was to be able to run the integration tests for all boosters locally using minishift as a smoke test.

**Comment by geoand** [comment]
So what exactly would be tested in this? I am not really clear on that...

**Comment by metacosm** [comment]
@geoand just running the integration tests like https://github.com/snowdrop/booster-common/blob/master/run_tests.sh does. Except in a function and isolating each test in a namespace to avoid conflicts / side effects. Also, probably settings things up for SSO and ConfigMap.

**Comment by geoand** [comment]
OK thanks, I'll need to look into it :)

**Comment by geoand** [comment]
I'll start working on merging the test code into the main script since now we have everything in place
